<?php


class ProspectedCompany extends BaseModel
{
    public function __construct()
    {
        global $dbConnectionAumet;

        parent::__construct($dbConnectionAumet, 'production.ProspectedCompany');
    }

    public function getById($id)
    {
        return parent::getByField('"ID"', $id);
    }

    public function addReturnID()
    {
        return $this->get('_id');
    }

    public function addAndLoad()
    {
        $this->Token = \Ramsey\Uuid\Uuid::uuid4();
        $this->UUID = \Ramsey\Uuid\Uuid::uuid4();
        $this->CreatedBy = 'ONEX';
        return parent::addAndLoadById('"ID"'); // TODO: Change the autogenerated stub
    }
}